name: Check code formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: |
          npm ci
        env:
          CI: false

      - name: Lint JS & TS
        run: |
          npm run lint

      - name: Lint rust
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
